
TRON_URL = 'TRON API ENDPOINT'
ASSET_ID = 'TRX_TEST'
OWNER_ADDRESS = 'OWNER ADDRESS'
SR_ADDRESS = "SR ADDRESS"
FROZEN_BALANCE = 1000000  # Amount in SUN (1 TRX = 1,000,000 SUN)
RESOURCE = 'ENERGY'  # Can be 'ENERGY' or 'BANDWIDTH'
TRON_NETWORK = "The TRON NETWORK"

API_SECRET_PATH = 'PATH TO FIREBLOCKS API SECRET'
with open(API_SECRET_PATH, 'r') as file:
    API_SECRET = file.read()
FIREBLOCKS_API_KEY = 'FIREBLOCKS API KEY'
SOURCE_VAULT_ACCOUNT_ID = 'FIREBLOCKS VAULT ACCOUNT ID'